name: Python construction

on:
    push:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Hacer checkout del proyecto
              uses: actions/checkout@v4

            - name: Configurar python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10' 

            - name: Instalar dependencias
              run: pip install -r requirements.txt

            - name: Ejecución de Pruebas
              run: pytest test_main.py
    
            - name: Compilación exitosa
              run: echo "Compilación exitosa"
